### ISSUE TITLE
Scarce error when closing search query field by pressing the 'x'

### ISSUE THREAD

**Issue by BjoernPetersen** [IIIuminator/EnQ#47] opened 2019-02-27 18:27 UTC
```
    java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at com.mikepenz.fastadapter.utils.DefaultItemListImpl.remove(DefaultItemListImpl.kt:41)
        at com.mikepenz.fastadapter.adapters.ModelAdapter.remove(ModelAdapter.kt:393)
        at com.ivoberger.enq.ui.fragments.parents.SongListFragment$enqueueEntry$1$1.invokeSuspend(SongListFragment.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6589)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by IIIuminator** [comment] 2019-02-28 10:29
Closing in favor of #46 as the root cause is the same

**Closed** 2019-02-28 10:29 UTC
Labels: bug
